version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - 13075:5432
    volumes:
      - postgres:/data/postgres
  backend:
    build: backend
    env_file: backend/.env
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: postgres
      PORT: 3000
    command: yarn start
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 13076:3000
    depends_on:
      - db
  frontend:
    build: frontend
    env_file: frontend/.env
    environment:
      REACT_APP_WS_HOST: ws://localhost:13076
      PORT: 3000
    command: yarn start
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 13077:3000
    depends_on:
      - backend

volumes:
  postgres:
